### ISSUE TITLE
程序在eh更新后无法使用

### ISSUE THREAD

**Issue by northtowertop** [ccloli/e-hentai-db#29]
如题，我不能确定是不是因为e站更新导致的，但是看了下停止的时间点的确是那段时间停下的，报错如下。

[
  '/www/server/nodejs/v14.17.6/bin/node',
  '/root/ehdb/e-hentai-db/scripts/sync.js',
  'exhentai.org'
]
got last posted = 1667489794
requesting page 0...
TypeError: Cannot read property 'map' of null
    at IncomingMessage.<anonymous> (/root/ehdb/e-hentai-db/scripts/sync.js:88:21)
    at IncomingMessage.emit (events.js:412:35)
    at endReadableNT (internal/streams/readable.js:1317:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)

**Comment by northtowertop** [comment]
看了下，貌似是因为ip被ban了。但是之前的时间规则用了半年多都还好。
